name: Build

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"

      - name: Go Tidy
        run: go mod tidy && git diff --exit-code

      - name: Go Mod
        run: go mod download

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: sklyarx
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: make docker-driver-push
